added file upload routes using multer
Sharif37/MudirDokan pull request #11
Opened 2024-11-08 16:12 UTC by Sharif37

user can upload multiple image of a product . Each product_id mach multiple image in one to many relationship . user can upload **8** images at a time . here i use **multer** middle-ware for upload file .

2024-11-09 16:23 UTC, Sharif37 commented
In this commit , i  added pagination and filtration   for all routes . i make it generalize for each routes . using pagination you can set custom limit and fetch portion of data from server each time . using filtration you can filters data based on all possible criteria . it covers all possible searching  done by users .

2024-11-11 15:40 UTC, tajmaun requested changes

2024-11-11 15:40 UTC, tajmaun commented on src/controllers/productController.ts
>  export async function getAllCategories(req: Request, res: Response) {
Follower proper name conventions 
req -> categroryRequest
res -> categoryResponse

2024-11-11 15:40 UTC, tajmaun commented on src/controllers/productController.ts
>  export async function getProductsByCategory(req: Request, res: Response) {
Follower proper name conventions
req -> productRequest
res -> productResponse

2024-11-11 15:40 UTC, tajmaun commented on src/controllers/productController.ts
> -    const products = await productService.getProductsByCategoryId(categoryId);
Add log here

2024-11-11 15:40 UTC, tajmaun commented on src/helper/addCategoryFilters.ts
> +    query = query.where("product_category.parent_category_id", "=", filters.parent_category_id);
be specific what sort query it is

2024-11-11 15:40 UTC, tajmaun commented on src/helper/addFiltration.ts
> +  if (table === "product") {
"product" declare it as constant

2024-11-11 15:40 UTC, tajmaun commented on src/helper/addFiltration.ts
> +   else if(table === "product_category"){
"product_category" declare it as constant if intend to use it again somewhere in the codebase

2024-11-11 15:40 UTC, tajmaun commented on src/helper/addProductFilters.ts
> +  req: Request,
be specific in naming

2024-11-11 15:40 UTC, tajmaun commented on src/helper/addProductFilters.ts
> +  // Filter by product_id (number)
z.coerce.number().safeParse(req.query.product_id).success
 
do this operation separately and use a variable with proper naming to understand its action.

2024-11-11 15:40 UTC, tajmaun commented on src/helper/addProductFilters.ts
> +  if (
same goes to here.

follow above comment

2024-11-11 15:40 UTC, tajmaun commented on src/helper/paginatedResults.ts
> +  req: Request,
use proper naming

2024-11-17 15:14 UTC, tajmaun approved these changes
Looks good

2024-11-17 15:15 UTC, merged